name: Build & Test CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    buildJob:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: npm i
            - name: Build packages
              run: npm  run build